# Generated by Django 4.1 on 2022-12-07 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='board',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='date',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='id',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='isAnonymous',
        ),
        migrations.AddField(
            model_name='complaints',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='auther',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.post')),
                ('isAnonymous', models.BooleanField()),
                ('board', models.CharField(max_length=50)),
            ],
            bases=('main.post',),
        ),
    ]
