# Generated by Django 4.1.4 on 2022-12-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_board_delete_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security_todo',
            name='status',
            field=models.IntegerField(),
        ),
    ]
