# Generated by Django 4.1.4 on 2022-12-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_security_todo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
    ]
