# Generated by Django 4.1.4 on 2022-12-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_convenient_delete_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.communitypost')),
            ],
            bases=('main.post',),
        ),
    ]
