# Generated by Django 4.1.4 on 2022-12-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_communitypost_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='board',
        ),
    ]
