# Generated by Django 4.1.4 on 2022-12-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_board'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='security_todo',
            new_name='SecurityTodo',
        ),
    ]
