# Generated by Django 4.1.4 on 2022-12-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_user_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('status', models.TextField()),
                ('space', models.IntegerField()),
            ],
        ),
    ]
