# Generated by Django 4.1.4 on 2022-12-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_calender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CCTV',
        ),
        migrations.DeleteModel(
            name='park',
        ),
    ]
